### ISSUE TITLE
Extension not loading the JS code logic - menu in BM not showing up

### ISSUE THREAD

**Issue by ClaudiuCudla** [mihai-vlc/bm-extender#3]
Hello @ionutvmi ,
Since April 16th, the extension has stopped loading and I confirmed with other colleagues that it's on their side too.
I tried locally and loaded the unpacked version and I found one issue in the manifest declaration that seems to be the cause of this.
In the `manifest.json` file, the URLs have a trailing slash at the end that seem to block the extension from working.
I don't have a lot of experience with Chrome extensions, but this change made it work for me - maybe you can test it on your side and see if that helps.
Thanks!

**Comment by mihai-vlc** [comment]
Indeed the new restricted permissions cased the issue.

I have modified them in 1.7.5
Unfortunately it might take a while until it reaches everybody due to the new web store review process.
Hopefully it will be published early next week, until then people can load the extension using the guidelines from: https://github.com/ionutvmi/bm-extender#install

**Comment by mihai-vlc** [comment]
Looks like the fix was published !
Please reopen this ticket if you still encounter issues.
